# Generated by Django 4.2.9 on 2024-01-31 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0002_alter_category_options_item"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="Category",
            new_name="category",
        ),
    ]
